---
title: "Simulation Summary (2S-PA Only)"
author: "Winnie Wing-Yee Tse"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r}
library(tidyverse)
```


```{r}
simres <- readRDS("simres_2spa_only.rds")
```

```{r}
simres_long <- simres %>%
  tibble::rowid_to_column("cond") %>%
  pivot_longer(
    bias.est_TSPA_meani:coverage.ci_TSPA_vars, 
    names_to = c("criteria", "method", "stat", "par"), 
    values_to = "value", 
    names_pattern = "(.*)_(.*)_(.*)(.)"
  )
```


## Bias

```{r}
simres_long %>%
  filter(criteria == "bias.est", stat == "mean", 
         par == "i") %>%
  mutate(n = as.factor(n)) %>%
  ggplot(aes(x = r_ni, y = value)) +
  geom_point(aes(shape = n, col = misspecify), 
             position = position_jitter(width = .01)) +
  # geom_line(aes(shape = n, col = misspecify)) +
  facet_grid(~ kappa2) +
  ylim(-.05, .2) +
  labs(title = "Bias for estimating mean intercept")
```

```{r}
simres_long %>%
  filter(criteria == "bias.est", stat == "mean", 
         par == "s") %>%
  mutate(n = as.factor(n)) %>%
  ggplot(aes(x = r_ni, y = value)) +
  geom_point(aes(shape = n, col = misspecify), 
             position = position_jitter(width = .01)) +
  # geom_line(aes(shape = n, col = misspecify)) +
  facet_grid(~ kappa2) +
  ylim(-.01, .12) +
  labs(title = "Bias for estimating mean slope")
```

## Standardized Bias

```{r}
simres_long %>%
  filter(criteria == "std_bias.est", stat == "mean", 
         par == "i") %>%
  mutate(n = as.factor(n)) %>%
  ggplot(aes(x = r_ni, y = value)) +
  geom_point(aes(shape = n, col = misspecify), 
             position = position_jitter(width = .01)) +
  # geom_line(aes(shape = n, col = misspecify)) +
  facet_grid(~ kappa2) +
  labs(title = "Bias for estimating mean intercept")
```

```{r}
simres_long %>%
  filter(criteria == "std_bias.est", stat == "mean", 
         par == "s") %>%
  mutate(n = as.factor(n)) %>%
  ggplot(aes(x = r_ni, y = value)) +
  geom_point(aes(shape = n, col = misspecify), 
             position = position_jitter(width = .01)) +
  # geom_line(aes(shape = n, col = misspecify)) +
  facet_grid(~ kappa2) +
  labs(title = "Bias for estimating mean slope")
```

## RMSE

```{r}
simres_long %>%
  filter(criteria == "rmse.est", stat == "mean", 
         par == "i") %>%
  mutate(n = as.factor(n)) %>%
  ggplot(aes(x = r_ni, y = value)) +
  geom_point(aes(shape = n, col = misspecify), 
             position = position_jitter(width = .01)) +
  # geom_line(aes(shape = n, col = misspecify)) +
  facet_grid(~ kappa2) +
  labs(title = "Bias for estimating mean intercept")
```

```{r}
simres_long %>%
  filter(criteria == "rmse.est", stat == "mean", 
         par == "s") %>%
  mutate(n = as.factor(n)) %>%
  ggplot(aes(x = r_ni, y = value)) +
  geom_point(aes(shape = n, col = misspecify), 
             position = position_jitter(width = .01)) +
  # geom_line(aes(shape = n, col = misspecify)) +
  facet_grid(~ kappa2) +
  labs(title = "Bias for estimating mean slope")
```


## Confidence Interval Converge

```{r}
simres_long %>%
  filter(criteria == "coverage.ci", stat == "mean", 
         par == "i") %>%
  mutate(n = as.factor(n)) %>%
  ggplot(aes(x = r_ni, y = value)) +
  geom_point(aes(shape = n, col = misspecify), 
             position = position_jitter(width = .01)) +
  # geom_line(aes(shape = n, col = misspecify)) +
  facet_grid(~ kappa2) +
  labs(title = "Bias for estimating mean intercept")
```

```{r}
simres_long %>%
  filter(criteria == "coverage.ci", stat == "mean", 
         par == "s") %>%
  mutate(n = as.factor(n)) %>%
  ggplot(aes(x = r_ni, y = value)) +
  geom_point(aes(shape = n, col = misspecify), 
             position = position_jitter(width = .01)) +
  # geom_line(aes(shape = n, col = misspecify)) +
  facet_grid(~ kappa2) +
  labs(title = "Bias for estimating mean slope")
```

