---
title: "Simulation Summary"
author: "Winnie Wing-Yee Tse"
date: "`r Sys.Date()`"
output: 
  pdf_document:
    toc: TRUE
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r message=FALSE}
library(tidyverse)
library(kableExtra)
```


```{r}
simres <- readRDS("simresults.rds")
```

```{r}
simres_long <- simres %>%
  tibble::rowid_to_column("cond") %>%
  pivot_longer(
    bias.est_PI_meani:coverage.ci_TSAPB_vars, 
    names_to = c("criteria", "method", "stat", "par"), 
    values_to = "value", 
    names_pattern = "(.*)_(.*)_(.*)(.)"
  )
```


## Bias

### Mean Intercept

```{r}
simres %>%
  filter(r_ni == 0) %>%
  select(misspecify, kappa2, n, 
         contains("bias.est") & contains("meani") & 
           !contains("std") & !contains("FI")) %>%
  rename_with(~ gsub("_meani.*", "", gsub(".*est_", "", .x))) %>%
  knitr::kable(
    booktabs = TRUE, 
    escape = FALSE, 
    digits = c(0, 2, 0, rep(3, 5)), 
    align = c(rep("l", 3), rep("r", 5)), 
    caption = "Bias of intercept (r\\_ni = 0)"
  ) %>%
  collapse_rows(1:3)
```

```{r}
simres %>%
  filter(r_ni == .25) %>%
  select(misspecify, kappa2, n, 
         contains("bias.est") & contains("meani") & 
           !contains("std") & !contains("FI")) %>%
  rename_with(~ gsub("_meani.*", "", gsub(".*est_", "", .x))) %>%
  knitr::kable(
    booktabs = TRUE, 
    escape = FALSE, 
    digits = c(0, 2, 0, rep(3, 5)), 
    align = c(rep("l", 3), rep("r", 5)), 
    caption = "Bias of intercept (r\\_ni = .25)"
  ) %>%
  collapse_rows(1:3)
```

```{r}
simres %>%
  filter(r_ni == .55) %>%
  select(misspecify, kappa2, n, 
         contains("bias.est") & contains("meani") & 
           !contains("std") & !contains("FI")) %>%
  rename_with(~ gsub("_meani.*", "", gsub(".*est_", "", .x))) %>%
  knitr::kable(
    booktabs = TRUE, 
    escape = FALSE, 
    digits = c(0, 2, 0, rep(3, 5)), 
    align = c(rep("l", 3), rep("r", 5)), 
    caption = "Bias of intercept (r\\_ni = .55)"
  ) %>%
  collapse_rows(1:3)
```

```{r}
simres_long %>%
  filter(criteria == "bias.est", stat == "mean", 
         par == "i") %>%
  mutate(n = as.factor(n)) %>%
  ggplot(aes(x = r_ni, y = value)) +
  geom_point(aes(shape = n, col = misspecify), 
             position = position_jitter(width = .01)) +
  # geom_line(aes(shape = n, col = misspecify)) +
  facet_grid(kappa2 ~ method) +
  # ylim(-.05, .2) +
  labs(x = "Proportion of noninvariant items/parameters", 
       y = "Bias", title = "Bias for estimating mean intercept")
```

### Mean Slope

```{r}
simres %>%
  filter(r_ni == 0) %>%
  select(misspecify, kappa2, n, 
         contains("bias.est") & contains("means") & 
           !contains("std") & !contains("FI")) %>%
  rename_with(~ gsub("_means.*", "", gsub(".*est_", "", .x))) %>%
  knitr::kable(
    booktabs = TRUE, 
    escape = FALSE, 
    digits = c(0, 2, 0, rep(3, 5)), 
    align = c(rep("l", 3), rep("r", 5)), 
    caption = "Bias of slope (r\\_ni = 0)"
  ) %>%
  collapse_rows(1:3)
```

```{r}
simres %>%
  filter(r_ni == .25) %>%
  select(misspecify, kappa2, n, 
         contains("bias.est") & contains("means") & 
           !contains("std") & !contains("FI")) %>%
  rename_with(~ gsub("_means.*", "", gsub(".*est_", "", .x))) %>%
  knitr::kable(
    booktabs = TRUE, 
    escape = FALSE, 
    digits = c(0, 2, 0, rep(3, 5)), 
    align = c(rep("l", 3), rep("r", 5)), 
    caption = "Bias of slope (r\\_ni = .25)"
  ) %>%
  collapse_rows(1:3)
```

```{r}
simres %>%
  filter(r_ni == .55) %>%
  select(misspecify, kappa2, n, 
         contains("bias.est") & contains("means") & 
           !contains("std") & !contains("FI")) %>%
  rename_with(~ gsub("_means.*", "", gsub(".*est_", "", .x))) %>%
  knitr::kable(
    booktabs = TRUE, 
    escape = FALSE, 
    digits = c(0, 2, 0, rep(3, 5)), 
    align = c(rep("l", 3), rep("r", 5)), 
    caption = "Bias of slope (r\\_ni = .55)"
  ) %>%
  collapse_rows(1:3)
```

```{r}
simres_long %>%
  filter(criteria == "bias.est", stat == "mean", 
         par == "s") %>%
  mutate(n = as.factor(n)) %>%
  ggplot(aes(x = r_ni, y = value)) +
  geom_point(aes(shape = n, col = misspecify), 
             position = position_jitter(width = .01)) +
  # geom_line(aes(shape = n, col = misspecify)) +
  facet_grid(kappa2 ~ method) +
  labs(x = "Proportion of noninvariant items/parameters", 
       y = "Bias", title = "Bias for estimating mean slope")
```

## Standardized Bias

### Mean Intercept

```{r}
simres %>%
  filter(r_ni == 0) %>%
  select(misspecify, kappa2, n, 
         contains("std_bias.est") & contains("meani") & !contains("FI")) %>%
  rename_with(~ gsub("_meani.*", "", gsub(".*est_", "", .x))) %>%
  knitr::kable(
    booktabs = TRUE, 
    escape = FALSE, 
    digits = c(0, 2, 0, rep(3, 5)), 
    align = c(rep("l", 3), rep("r", 5)), 
    caption = "Standardized Bias of intercept (r\\_ni = 0)"
  ) %>%
  collapse_rows(1:3)
```

```{r}
simres %>%
  filter(r_ni == .25) %>%
  select(misspecify, kappa2, n, 
         contains("std_bias.est") & contains("meani") & !contains("FI")) %>%
  rename_with(~ gsub("_meani.*", "", gsub(".*est_", "", .x))) %>%
  knitr::kable(
    booktabs = TRUE, 
    escape = FALSE, 
    digits = c(0, 2, 0, rep(3, 5)), 
    align = c(rep("l", 3), rep("r", 5)), 
    caption = "Standardized Bias of intercept (r\\_ni = .25)"
  ) %>%
  collapse_rows(1:3)
```

```{r}
simres %>%
  filter(r_ni == .55) %>%
  select(misspecify, kappa2, n, 
         contains("std_bias.est") & contains("meani") & !contains("FI")) %>%
  rename_with(~ gsub("_meani.*", "", gsub(".*est_", "", .x))) %>%
  knitr::kable(
    booktabs = TRUE, 
    escape = FALSE, 
    digits = c(0, 2, 0, rep(3, 5)), 
    align = c(rep("l", 3), rep("r", 5)), 
    caption = "Standardized Bias of intercept (r\\_ni = .55)"
  ) %>%
  collapse_rows(1:3)
```

```{r}
simres_long %>%
  filter(criteria == "std_bias.est", stat == "mean", 
         par == "i") %>%
  mutate(n = as.factor(n)) %>%
  ggplot(aes(x = r_ni, y = value)) +
  geom_point(aes(shape = n, col = misspecify), 
             position = position_jitter(width = .01)) +
  # geom_line(aes(shape = n, col = misspecify)) +
  facet_grid(kappa2 ~ method) +
  labs(x = "Proportion of noninvariant items/parameters", 
       y = "Standardized bias", 
       title = "Standardized Bias for estimating mean intercept")
```

### Mean slope

```{r}
simres %>%
  filter(r_ni == 0) %>%
  select(misspecify, kappa2, n, 
         contains("std_bias.est") & contains("means") & !contains("FI")) %>%
  rename_with(~ gsub("_means.*", "", gsub(".*est_", "", .x))) %>%
  knitr::kable(
    booktabs = TRUE, 
    escape = FALSE, 
    digits = c(0, 2, 0, rep(3, 5)), 
    align = c(rep("l", 3), rep("r", 5)), 
    caption = "Standardized Bias of slope (r\\_ni = 0)"
  ) %>%
  collapse_rows(1:3)
```

```{r}
simres %>%
  filter(r_ni == .25) %>%
  select(misspecify, kappa2, n, 
         contains("std_bias.est") & contains("means") & !contains("FI")) %>%
  rename_with(~ gsub("_means.*", "", gsub(".*est_", "", .x))) %>%
  knitr::kable(
    booktabs = TRUE, 
    escape = FALSE, 
    digits = c(0, 2, 0, rep(3, 5)), 
    align = c(rep("l", 3), rep("r", 5)), 
    caption = "Standardized Bias of slope (r\\_ni = .25)"
  ) %>%
  collapse_rows(1:3)
```

```{r}
simres %>%
  filter(r_ni == .55) %>%
  select(misspecify, kappa2, n, 
         contains("std_bias.est") & contains("means") & !contains("FI")) %>%
  rename_with(~ gsub("_means.*", "", gsub(".*est_", "", .x))) %>%
  knitr::kable(
    booktabs = TRUE, 
    escape = FALSE, 
    digits = c(0, 2, 0, rep(3, 5)), 
    align = c(rep("l", 3), rep("r", 5)), 
    caption = "Standardized Bias of slope (r\\_ni = .55)"
  ) %>%
  collapse_rows(1:3)
```

```{r}
simres_long %>%
  filter(criteria == "std_bias.est", stat == "mean", 
         par == "s") %>%
  mutate(n = as.factor(n)) %>%
  ggplot(aes(x = r_ni, y = value)) +
  geom_point(aes(shape = n, col = misspecify), 
             position = position_jitter(width = .01)) +
  # geom_line(aes(shape = n, col = misspecify)) +
  facet_grid(kappa2 ~ method) +
  labs(x = "Proportion of noninvariant items/parameters", 
       y = "Standardized bias", 
       title = "Standardized Bias for estimating mean slope")
```

## RMSE

### Mean Intercept

```{r}
simres %>%
  filter(r_ni == 0) %>%
  select(misspecify, kappa2, n, 
         contains("rmse.est") & contains("meani") & !contains("FI")) %>%
  rename_with(~ gsub("_meani.*", "", gsub(".*est_", "", .x))) %>%
  knitr::kable(
    booktabs = TRUE, 
    escape = FALSE, 
    digits = c(0, 2, 0, rep(3, 5)), 
    align = c(rep("l", 3), rep("r", 5)), 
    caption = "RMSE of intercept (r\\_ni = 0)"
  ) %>%
  collapse_rows(1:3)
```

```{r}
simres %>%
  filter(r_ni == .25) %>%
  select(misspecify, kappa2, n, 
         contains("rmse.est") & contains("meani") & !contains("FI")) %>%
  rename_with(~ gsub("_meani.*", "", gsub(".*est_", "", .x))) %>%
  knitr::kable(
    booktabs = TRUE, 
    escape = FALSE, 
    digits = c(0, 2, 0, rep(3, 5)), 
    align = c(rep("l", 3), rep("r", 5)), 
    caption = "RMSE of intercept (r\\_ni = .25)"
  ) %>%
  collapse_rows(1:3)
```

```{r}
simres %>%
  filter(r_ni == .55) %>%
  select(misspecify, kappa2, n, 
         contains("rmse.est") & contains("meani") & !contains("FI")) %>%
  rename_with(~ gsub("_meani.*", "", gsub(".*est_", "", .x))) %>%
  knitr::kable(
    booktabs = TRUE, 
    escape = FALSE, 
    digits = c(0, 2, 0, rep(3, 5)), 
    align = c(rep("l", 3), rep("r", 5)), 
    caption = "RMSE of intercept (r\\_ni = .55)"
  ) %>%
  collapse_rows(1:3)
```

```{r}
simres_long %>%
  filter(criteria == "rmse.est", stat == "mean", 
         par == "i") %>%
  mutate(n = as.factor(n)) %>%
  ggplot(aes(x = r_ni, y = value)) +
  geom_point(aes(shape = n, col = misspecify), 
             position = position_jitter(width = .01)) +
  # geom_line(aes(shape = n, col = misspecify)) +
  facet_grid(kappa2 ~ method) +
  labs(x = "Proportion of noninvariant items/parameters", 
       y = "Root mean squared error", 
       title = "RMSE for estimating mean intercept")
```

### Mean Slope

```{r}
simres %>%
  filter(r_ni == 0) %>%
  select(misspecify, kappa2, n, 
         contains("rmse.est") & contains("means") & !contains("FI")) %>%
  rename_with(~ gsub("_means.*", "", gsub(".*est_", "", .x))) %>%
  knitr::kable(
    booktabs = TRUE, 
    escape = FALSE, 
    digits = c(0, 2, 0, rep(3, 5)), 
    align = c(rep("l", 3), rep("r", 5)), 
    caption = "RMSE of slope (r\\_ni = 0)"
  ) %>%
  collapse_rows(1:3)
```

```{r}
simres %>%
  filter(r_ni == .25) %>%
  select(misspecify, kappa2, n, 
         contains("rmse.est") & contains("means") & !contains("FI")) %>%
  rename_with(~ gsub("_means.*", "", gsub(".*est_", "", .x))) %>%
  knitr::kable(
    booktabs = TRUE, 
    escape = FALSE, 
    digits = c(0, 2, 0, rep(3, 5)), 
    align = c(rep("l", 3), rep("r", 5)), 
    caption = "RMSE of slope (r\\_ni = .25)"
  ) %>%
  collapse_rows(1:3)
```

```{r}
simres %>%
  filter(r_ni == .55) %>%
  select(misspecify, kappa2, n, 
         contains("rmse.est") & contains("means") & !contains("FI")) %>%
  rename_with(~ gsub("_means.*", "", gsub(".*est_", "", .x))) %>%
  knitr::kable(
    booktabs = TRUE, 
    escape = FALSE, 
    digits = c(0, 2, 0, rep(3, 5)), 
    align = c(rep("l", 3), rep("r", 5)), 
    caption = "RMSE of slope (r\\_ni = .55)"
  ) %>%
  collapse_rows(1:3)
```

```{r}
simres_long %>%
  filter(criteria == "rmse.est", stat == "mean", 
         par == "s") %>%
  mutate(n = as.factor(n)) %>%
  ggplot(aes(x = r_ni, y = value)) +
  geom_point(aes(shape = n, col = misspecify), 
             position = position_jitter(width = .01)) +
  # geom_line(aes(shape = n, col = misspecify)) +
  facet_grid(kappa2 ~ method) +
  labs(x = "Proportion of noninvariant items/parameters", 
       y = "Root mean squared error", 
       title = "RMSE for estimating mean slope")
```


## Confidence Interval Converge

### Mean Intercept

```{r}
simres %>%
  filter(r_ni == 0) %>%
  select(misspecify, kappa2, n, 
         contains("coverage.ci") & contains("meani") & !contains("FI")) %>%
  rename_with(~ gsub("_meani.*", "", gsub(".*ci_", "", .x))) %>%
  knitr::kable(
    booktabs = TRUE, 
    escape = FALSE, 
    digits = c(0, 2, 0, rep(3, 5)), 
    align = c(rep("l", 3), rep("r", 5)), 
    caption = "Coverage of intercept (r\\_ni = 0)"
  ) %>%
  collapse_rows(1:3)
```

```{r}
simres %>%
  filter(r_ni == .25) %>%
  select(misspecify, kappa2, n, 
         contains("coverage.ci") & contains("meani") & !contains("FI")) %>%
  rename_with(~ gsub("_meani.*", "", gsub(".*ci_", "", .x))) %>%
  knitr::kable(
    booktabs = TRUE, 
    escape = FALSE, 
    digits = c(0, 2, 0, rep(3, 5)), 
    align = c(rep("l", 3), rep("r", 5)), 
    caption = "Converage of intercept (r\\_ni = .25)"
  ) %>%
  collapse_rows(1:3)
```

```{r}
simres %>%
  filter(r_ni == .55) %>%
  select(misspecify, kappa2, n, 
         contains("coverage.ci") & contains("meani") & !contains("FI")) %>%
  rename_with(~ gsub("_meani.*", "", gsub(".*ci_", "", .x))) %>%
  knitr::kable(
    booktabs = TRUE, 
    escape = FALSE, 
    digits = c(0, 2, 0, rep(3, 5)), 
    align = c(rep("l", 3), rep("r", 5)), 
    caption = "Coverage of intercept (r\\_ni = .55)"
  ) %>%
  collapse_rows(1:3)
```

```{r}
simres_long %>%
  filter(criteria == "coverage.ci", stat == "mean", 
         par == "i") %>%
  mutate(n = as.factor(n)) %>%
  ggplot(aes(x = r_ni, y = value)) +
  geom_point(aes(shape = n, col = misspecify), 
             position = position_jitter(width = .01)) +
  # geom_line(aes(shape = n, col = misspecify)) +
  facet_grid(kappa2 ~ method) +
  labs(x = "Proportion of noninvariant items/parameters", 
       y = "Confidence interval converage", 
       title = "Coverage for estimating mean intercept")
```

### Mean Slope

```{r}
simres %>%
  filter(r_ni == 0) %>%
  select(misspecify, kappa2, n, 
         contains("coverage.ci") & contains("means") & !contains("FI")) %>%
  rename_with(~ gsub("_means.*", "", gsub(".*ci_", "", .x))) %>%
  knitr::kable(
    booktabs = TRUE, 
    escape = FALSE, 
    digits = c(0, 2, 0, rep(3, 5)), 
    align = c(rep("l", 3), rep("r", 5)), 
    caption = "Coverage of slope (r\\_ni = 0)"
  ) %>%
  collapse_rows(1:3)
```

```{r}
simres %>%
  filter(r_ni == .25) %>%
  select(misspecify, kappa2, n, 
         contains("coverage.ci") & contains("means") & !contains("FI")) %>%
  rename_with(~ gsub("_means.*", "", gsub(".*ci_", "", .x))) %>%
  knitr::kable(
    booktabs = TRUE, 
    escape = FALSE, 
    digits = c(0, 2, 0, rep(3, 5)), 
    align = c(rep("l", 3), rep("r", 5)), 
    caption = "Converage of slope (r\\_ni = .25)"
  ) %>%
  collapse_rows(1:3)
```

```{r}
simres %>%
  filter(r_ni == .55) %>%
  select(misspecify, kappa2, n, 
         contains("coverage.ci") & contains("means") & !contains("FI")) %>%
  rename_with(~ gsub("_means.*", "", gsub(".*ci_", "", .x))) %>%
  knitr::kable(
    booktabs = TRUE, 
    escape = FALSE, 
    digits = c(0, 2, 0, rep(3, 5)), 
    align = c(rep("l", 3), rep("r", 5)), 
    caption = "Coverage of slope (r\\_ni = .55)"
  ) %>%
  collapse_rows(1:3)
```

```{r}
simres_long %>%
  filter(criteria == "coverage.ci", stat == "mean", 
         par == "s") %>%
  mutate(n = as.factor(n)) %>%
  ggplot(aes(x = r_ni, y = value)) +
  geom_point(aes(shape = n, col = misspecify), 
             position = position_jitter(width = .01)) +
  # geom_line(aes(shape = n, col = misspecify)) +
  facet_grid(kappa2 ~ method) +
  labs(x = "Proportion of noninvariant items/parameters", 
       y = "Confidence interval converage", 
       title = "Coverage for estimating mean slope")
```

## Reevaluate (Compute Rejection Rates)

```{r}
reevaluate <- function(condition, results, fixed_objects = NULL) {
  # Specify population value
  methods <- c("PI", "FI", "AwG", "TSPAA", "TSPAB")
  pars <- c("meani", "means", "vari", "vars")
  pop <- rep(c(fixed_objects$kappa1, condition$kappa2, 
               diag(fixed_objects$Psi_growth)), each = length(methods))
  results_est <- results[ , grep("^est_", colnames(results))]
  results_ase <- results[ , grep("^ase_", colnames(results))]
  results_ci <- matrix(
    as.matrix(
      rbind(results_est - qnorm(.975) * results_ase,
            results_est + qnorm(.975) * results_ase)
    ),
    nrow = nrow(results)
  )
  ret_ci <- SimDesign::ECR(
    sweep(results_ci, 2, rep(pop, each = 2), "-"),
    parameter = 0
  )
  names(ret_ci) <- gsub("est_", "ci_", colnames(results_est))
  ncols <- ncol(results_ci)
  ci_lo <- results_ci[, seq_len(ncols) %% 2 == 1] < 0 # lower < 0
  ci_up <- results_ci[, seq_len(ncols) %% 2 == 0] > 0 # upper > 0
  # if contains 0, TRUE + TRUE; otherwise, TRUE + FALSE / FALSE + FALSE
  rej <- ci_lo + ci_up < 2
  ret_rate <- colSums(rej) / nrow(results)
  names(ret_rate) <- gsub("est_", "rate_", colnames(results_est))
  ret <- c(
    bias = SimDesign::bias(
      results_est,
      parameter = pop),
    std_bias = SimDesign::bias(
      results_est,
      parameter = pop,
      type = "standardized"),
    rmse = SimDesign::RMSE(
      results_est,
      parameter = pop
    ),
    coverage = ret_ci, 
    rej = ret_rate
  )
  ret
}
```

```{r}
simres_re <- SimDesign::reSummarise(
  reevaluate, 
  dir = "simdetails/", 
  fixed_objects = list(
      # ucov = UCOV,
      n_waves = 4,
      n_items = 5,
      theta_growth = .50,
      kappa1 = 0,
      Psi_growth = matrix(c(.5, .089, .089, .1), nrow = 2),
      kappa3 = -0.01,
      phi33 = 0.004,
      lambda_vec = c(.8, .5, .7, .65, .7),
      nu_vec = c(0, .5, -.25, .25, -.5),
      lambda_deviation =
        list(`0.25` = rbind(0, 0, 0, 0, seq(0, 0.3, length.out = 4)),
             `0.55` = rbind(0, 0,
                            c(0, 0.2, 0.3, 0.1),
                            c(0, -0.05, 0, 0.05),
                            seq(0, 0.3, length.out = 4))),
      nu_deviation =
        list(`0.25` = rbind(0, 0, 0,
                            seq(0, 0.75, length.out = 4),
                            c(0, 0.125, -0.125, 0)),
             `0.55` = rbind(c(0, 0.75, 0.5, 0.25),
                            c(0, 0.25, 0, 0.50),
                            0,
                            seq(0, 0.75, length.out = 4),
                            c(0, 0.125, -0.125, 0))),
      ar_rho = .20  # autoregressive coefficient
    )
)
```


## Type I Error Rate

### Mean Intercept

```{r}
simres_re %>%
  filter(r_ni == 0, kappa2 == 0) %>%
  select(misspecify, n, 
         contains("rej.rate") & contains("meani") & !contains("FI")) %>%
  mutate_at(vars(contains("rej.rate")), ~ . * 100) %>%
  rename_with(~ gsub("_meani.*", "", gsub(".*rate_", "", .x))) %>%
  knitr::kable(
    booktabs = TRUE, 
    escape = FALSE, 
    digits = c(0, 0, rep(2, 5)), 
    align = c(rep("l", 3), rep("r", 5)), 
    caption = "Type I error rate (\\%) of intercept (r\\_ni = 0)"
  ) %>%
  collapse_rows(1:3)
```

```{r}
simres_re %>%
  filter(r_ni == .25, kappa2 == 0) %>%
  select(misspecify, n, 
         contains("rej.rate") & contains("meani") & !contains("FI")) %>%
  mutate_at(vars(contains("rej.rate")), ~ . * 100) %>%
  rename_with(~ gsub("_meani.*", "", gsub(".*rate_", "", .x))) %>%
  knitr::kable(
    booktabs = TRUE, 
    escape = FALSE, 
    digits = c(0, 0, rep(2, 5)), 
    align = c(rep("l", 3), rep("r", 5)), 
    caption = "Type I error rate (\\%) of intercept (r\\_ni = .25)"
  ) %>%
  collapse_rows(1:3)
```

```{r}
simres_re %>%
  filter(r_ni == .55, kappa2 == 0) %>%
  select(misspecify, n, 
         contains("rej.rate") & contains("meani") & !contains("FI")) %>%
  mutate_at(vars(contains("rej.rate")), ~ . * 100) %>%
  rename_with(~ gsub("_meani.*", "", gsub(".*rate_", "", .x))) %>%
  knitr::kable(
    booktabs = TRUE, 
    escape = FALSE, 
    digits = c(0, 0, rep(2, 5)), 
    align = c(rep("l", 3), rep("r", 5)), 
    caption = "Type I error rate (\\%) of intercept (r\\_ni = .55)"
  ) %>%
  collapse_rows(1:3)
```

### Mean Slope

```{r}
simres_re %>%
  filter(r_ni == 0, kappa2 == 0) %>%
  select(misspecify, n, 
         contains("rej.rate") & contains("means") & !contains("FI")) %>%
  mutate_at(vars(contains("rej.rate")), ~ . * 100) %>%
  rename_with(~ gsub("_means.*", "", gsub(".*rate_", "", .x))) %>%
  knitr::kable(
    booktabs = TRUE, 
    escape = FALSE, 
    digits = c(0, 0, rep(2, 5)), 
    align = c(rep("l", 3), rep("r", 5)), 
    caption = "Type I error rate (\\%) of slope (r\\_ni = 0)"
  ) %>%
  collapse_rows(1:3)
```

```{r}
simres_re %>%
  filter(r_ni == .25, kappa2 == 0) %>%
  select(misspecify, n, 
         contains("rej.rate") & contains("means") & !contains("FI")) %>%
  mutate_at(vars(contains("rej.rate")), ~ . * 100) %>%
  rename_with(~ gsub("_means.*", "", gsub(".*rate_", "", .x))) %>%
  knitr::kable(
    booktabs = TRUE, 
    escape = FALSE, 
    digits = c(0, 0, rep(2, 5)), 
    align = c(rep("l", 3), rep("r", 5)), 
    caption = "Type I error rate (\\%) of slope (r\\_ni = .25)"
  ) %>%
  collapse_rows(1:3)
```

```{r}
simres_re %>%
  filter(r_ni == .55, kappa2 == 0) %>%
  select(misspecify, n, 
         contains("rej.rate") & contains("means") & !contains("FI")) %>%
  mutate_at(vars(contains("rej.rate")), ~ . * 100) %>%
  rename_with(~ gsub("_means.*", "", gsub(".*rate_", "", .x))) %>%
  knitr::kable(
    booktabs = TRUE, 
    escape = FALSE, 
    digits = c(0, 0, rep(2, 5)), 
    align = c(rep("l", 3), rep("r", 5)), 
    caption = "Type I error rate (\\%) of slope (r\\_ni = .55)"
  ) %>%
  collapse_rows(1:3)
```

## Power

### Mean Intercept

```{r}
simres_re %>%
  filter(r_ni == 0, kappa2 == .25) %>%
  select(misspecify, n, 
         contains("rej.rate") & contains("meani") & !contains("FI")) %>%
  mutate_at(vars(contains("rej.rate")), ~ . * 100) %>%
  rename_with(~ gsub("_meani.*", "", gsub(".*rate_", "", .x))) %>%
  knitr::kable(
    booktabs = TRUE, 
    escape = FALSE, 
    digits = c(0, 0, rep(2, 5)), 
    align = c(rep("l", 3), rep("r", 5)), 
    caption = "Power (\\%) of intercept (r\\_ni = 0)"
  ) %>%
  collapse_rows(1:3)
```

```{r}
simres_re %>%
  filter(r_ni == .25, kappa2 == .25) %>%
  select(misspecify, n, 
         contains("rej.rate") & contains("meani") & !contains("FI")) %>%
  mutate_at(vars(contains("rej.rate")), ~ . * 100) %>%
  rename_with(~ gsub("_meani.*", "", gsub(".*rate_", "", .x))) %>%
  knitr::kable(
    booktabs = TRUE, 
    escape = FALSE, 
    digits = c(0, 0, rep(2, 5)), 
    align = c(rep("l", 3), rep("r", 5)), 
    caption = "Power (\\%) of intercept (r\\_ni = .25)"
  ) %>%
  collapse_rows(1:3)
```

```{r}
simres_re %>%
  filter(r_ni == .55, kappa2 == .25) %>%
  select(misspecify, n, 
         contains("rej.rate") & contains("meani") & !contains("FI")) %>%
  mutate_at(vars(contains("rej.rate")), ~ . * 100) %>%
  rename_with(~ gsub("_meani.*", "", gsub(".*rate_", "", .x))) %>%
  knitr::kable(
    booktabs = TRUE, 
    escape = FALSE, 
    digits = c(0, 0, rep(2, 5)), 
    align = c(rep("l", 3), rep("r", 5)), 
    caption = "Power (\\%) of intercept (r\\_ni = .55)"
  ) %>%
  collapse_rows(1:3)
```

### Mean Slope

```{r}
simres_re %>%
  filter(r_ni == 0, kappa2 == .25) %>%
  select(misspecify, n, 
         contains("rej.rate") & contains("means") & !contains("FI")) %>%
  mutate_at(vars(contains("rej.rate")), ~ . * 100) %>%
  rename_with(~ gsub("_means.*", "", gsub(".*rate_", "", .x))) %>%
  knitr::kable(
    booktabs = TRUE, 
    escape = FALSE, 
    digits = c(0, 0, rep(2, 5)), 
    align = c(rep("l", 3), rep("r", 5)), 
    caption = "Power (\\%) of slope (r\\_ni = 0)"
  ) %>%
  collapse_rows(1:3)
```

```{r}
simres_re %>%
  filter(r_ni == .25, kappa2 == .25) %>%
  select(misspecify, n, 
         contains("rej.rate") & contains("means") & !contains("FI")) %>%
  mutate_at(vars(contains("rej.rate")), ~ . * 100) %>%
  rename_with(~ gsub("_means.*", "", gsub(".*rate_", "", .x))) %>%
  knitr::kable(
    booktabs = TRUE, 
    escape = FALSE, 
    digits = c(0, 0, rep(2, 5)), 
    align = c(rep("l", 3), rep("r", 5)), 
    caption = "Power (\\%) of slope (r\\_ni = .25)"
  ) %>%
  collapse_rows(1:3)
```

```{r}
simres_re %>%
  filter(r_ni == .55, kappa2 == .25) %>%
  select(misspecify, n, 
         contains("rej.rate") & contains("means") & !contains("FI")) %>%
  mutate_at(vars(contains("rej.rate")), ~ . * 100) %>%
  rename_with(~ gsub("_means.*", "", gsub(".*rate_", "", .x))) %>%
  knitr::kable(
    booktabs = TRUE, 
    escape = FALSE, 
    digits = c(0, 0, rep(2, 5)), 
    align = c(rep("l", 3), rep("r", 5)), 
    caption = "Power (\\%) of slope (r\\_ni = .55)"
  ) %>%
  collapse_rows(1:3)
```

